apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  labels:
    app: proxy-service
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: https
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    app: proxy-service
